const std = @import("std");

const chapters_data = @embedFile("chapters-data.json");
const ar_data = @embedFile("verses_ar_original.json");
const en_data = @embedFile("verses_en_sam-gerrans_with-notes.json");
const notes_data = @embedFile("notes_en_sam-gerrans.json");

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    var arena: std.heap.ArenaAllocator = .init(gpa);
    defer arena.deinit();
    const arena_alloc = arena.allocator();

    const args = try init.minimal.args.toSlice(arena_alloc);
    const io = init.io;
    if (args.len <= 1) return;

    const file = try std.Io.Dir.cwd().createFile(io, args[1], .{
        .read = true,
        .permissions = std.Io.File.Permissions.fromMode(0o644),
        .truncate = true,
    });
    defer file.close(io);

    var buffer: [4096]u8 = undefined;

    var file_writer = file.writer(io, &buffer);
    const writer = &file_writer.interface;

    try writer.writeAll("// THIS FILE IS GENERATED BY assets/embed_json.zig, DONT EDIT\n\n");

    try writer.writeAll("#ifndef QURANITE_DATA_HPP\n#define QURANITE_DATA_HPP\n\n");
    try writer.writeAll("inline constexpr const char* k_chapters_data = R\"json(\n");

    try writer.writeAll(chapters_data);
    try writer.writeAll("\n)json\";\n\n");

    try writer.writeAll("inline constexpr const char* k_ar_data = R\"json(\n");

    try writer.writeAll(ar_data);
    try writer.writeAll("\n)json\";\n\n");

    try writer.writeAll("inline constexpr const char* k_en_data = R\"json(\n");

    try writer.writeAll(en_data);
    try writer.writeAll("\n)json\";\n\n");

    try writer.writeAll("inline constexpr const char* k_notes_data = R\"json(\n");

    try writer.writeAll(notes_data);
    try writer.writeAll("\n)json\";\n\n");

    try writer.writeAll("#endif // QURANITE_DATA_HPP");

    try writer.flush();
}
