#!/usr/bin/env bash
args=()
for arg in "$@"; do
  case "$arg" in
    -I/usr/include|-I/usr/include/) 
      args+=("-idirafter" "/usr/include")
      ;;
    *) args+=("$arg") ;;
  esac
done
exec zig c++ "${args[@]}"
